In [16]:
from PIL import Image
import numpy as np

In [22]:
A = np.array(Image.open("bird_small.png"))

In [54]:
A[:,:,0]

array([[219, 230, 226, ...,  14,  13,  12],
       [230, 224, 226, ...,  16,  14,  11],
       [228, 228, 220, ...,  14,  13,  11],
       ...,
       [ 15,  18,  18, ...,  81,  70,  72],
       [ 16,  17,  20, ...,  80,  68,  59],
       [ 15,  20,  18, ...,  65,  58,  52]], dtype=uint8)

In [52]:
A

array([[[219, 180, 103],
        [230, 185, 116],
        [226, 186, 110],
        ...,
        [ 14,  15,  13],
        [ 13,  15,  12],
        [ 12,  14,  12]],

       [[230, 193, 119],
        [224, 192, 120],
        [226, 192, 124],
        ...,
        [ 16,  16,  13],
        [ 14,  15,  10],
        [ 11,  14,   9]],

       [[228, 191, 123],
        [228, 191, 121],
        [220, 185, 118],
        ...,
        [ 14,  16,  13],
        [ 13,  13,  11],
        [ 11,  15,  10]],

       ...,

       [[ 15,  18,  16],
        [ 18,  21,  18],
        [ 18,  19,  16],
        ...,
        [ 81,  45,  45],
        [ 70,  43,  35],
        [ 72,  51,  43]],

       [[ 16,  17,  17],
        [ 17,  18,  19],
        [ 20,  19,  20],
        ...,
        [ 80,  38,  40],
        [ 68,  39,  40],
        [ 59,  43,  42]],

       [[ 15,  19,  19],
        [ 20,  20,  18],
        [ 18,  19,  17],
        ...,
        [ 65,  43,  39],
        [ 58,  37,  38],
        [ 52,  39,  34]]

In [43]:
np.array([ 
             [[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]
           ])

(2, 2, 3)

In [41]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.array([1]).shape

NameError: name 'np' is not defined

In [20]:
np.array([[[3]]]).shape

(1, 1, 1)

In [ ]:
s